# Generated by Django 2.1.3 on 2018-12-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spotify_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('access_token', models.CharField(default='', max_length=200)),
                ('scope', models.CharField(default='', max_length=200)),
                ('expires_in', models.IntegerField(default=0)),
                ('refresh_token', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
