# Generated by Django 2.1.3 on 2019-03-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_connection', '0002_spotify_favorite_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotify_Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(default='', max_length=30)),
                ('track_name', models.CharField(default='', max_length=30)),
                ('track_artist_name', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
