# Generated by Django 2.1.3 on 2019-03-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_connection', '0003_spotify_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotify_track',
            old_name='track_artist_name',
            new_name='album_name',
        ),
        migrations.AddField(
            model_name='spotify_track',
            name='album_image',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='spotify_track',
            name='album_uri',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='spotify_track',
            name='artist_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='spotify_track',
            name='artist_uri',
            field=models.CharField(default='', max_length=30),
        ),
    ]
